<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <RootNamespace>ExFat</RootNamespace>

  </PropertyGroup>

  <PropertyGroup>

    <Title>ExFat Core</Title>
    <Description>exFAT core module for basic I/O</Description>

  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework.CompareTo(`net461`))' &gt;= 0">
    <PackageReference Include="System.Memory" Version="*" />
    <PackageReference Include="System.ValueTuple" Version="*" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework.CompareTo(`net461`))' &lt; 0">
    <PackageReference Include="System.Memory" Version="4.5.*" />
    <PackageReference Include="System.ValueTuple" Version="4.5.*" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LTRData.DiscUtils.Streams" Version="*" />
  </ItemGroup>
  
</Project>
