<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <RootNamespace>ExFat</RootNamespace>

  </PropertyGroup>

  <PropertyGroup>

    <Title>ExFat Core</Title>
    <Description>exFAT core module for basic I/O</Description>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.4" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
  </ItemGroup>

  <ItemGroup>

    <Reference Include="DiscUtils.Streams">
      <HintPath>$(DiscUtilsPath)\DiscUtils.Streams.dll</HintPath>
    </Reference>

  </ItemGroup>
  
</Project>