<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ExFat.DiscUtils</RootNamespace>
    <TargetFrameworks>net9.0;net48;net46</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Environment\exFAT.vhdx.gz" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\ExFat.Core\Properties\ProductInfo.cs" Link="Properties\ProductInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Environment\exFAT.vhdx.gz" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" />
    <PackageReference Include="xunit" Version="*" />
    <PackageReference Include="coverlet.collector" Version="*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework.CompareTo(`net462`))' &lt; 0">
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework.CompareTo(`net462`))' &gt;= 0">
    <PackageReference Include="xunit.runner.visualstudio" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExFat.Core\ExFat.Core.csproj" />
    <ProjectReference Include="..\ExFat.DiscUtils\ExFat.DiscUtils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LTRData.DiscUtils.Core" Version="*" />
    <PackageReference Include="LTRData.DiscUtils.Streams" Version="*" />
    <PackageReference Include="LTRData.DiscUtils.Vhdx" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
  
</Project>
