<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <RootNamespace>ExFat.DiscUtils</RootNamespace>
    
  </PropertyGroup>
  
  <PropertyGroup>

    <Title>ExFat DiscUtils</Title>
    <Description>DiscUtils wrapper for ExFAT</Description>

  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="5.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\ExFat.Core\ExFat.Core.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="LTRData.DiscUtils.Core" Version="1.0.0" />
    <PackageReference Include="LTRData.DiscUtils.Streams" Version="1.0.0" />
  </ItemGroup>

</Project>
