<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ExFat.Generator</RootNamespace>
    <AssemblyName>ExFat.Generator</AssemblyName>
    <TargetFrameworks>net7.0;net48;net46</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Company>picrap</Company>
    <Decription>Internal application to generate test disk</Decription>
    <Title>ExFat generator</Title>
    <Configuration>Release</Configuration>
    <Copyright>MIT license https://opensource.org/licenses/MIT</Copyright>
    <FileVersion>0.9.16</FileVersion>
    <InformationalVersion>0.9.16</InformationalVersion>
    <Product>ExFat</Product>
    <Title>ExFat.Generator</Title>
    <Version>0.9.16.0</Version>

  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\ExFat.Core\ExFat.Core.csproj" />
    <ProjectReference Include="..\ExFat.DiscUtils.Tests\ExFat.DiscUtils.Tests.csproj" />
    <ProjectReference Include="..\ExFat.DiscUtils\ExFat.DiscUtils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LTRData.DiscUtils.Core" Version="*" />
    <PackageReference Include="LTRData.DiscUtils.Streams" Version="*" />
    <PackageReference Include="LTRData.DiscUtils.Vhdx" Version="*" />
  </ItemGroup>

</Project>
